name: heroku-jupyter
dependencies:
  # bind notebook version (compatibility to pgcontents)
  - notebook = 4
  - ipywidgets
  - requests
  # bind ipython version (compatibility to pgcontents)
  - ipython = 5
  # get dependencies for pgcontents
  - certifi
  - click
  - cryptography 
  - mako
  - psycopg2
  - six
  - sqlalchemy
  - nose
#  - numpy
#  - matplotlib
#  - pandas
#  - seaborn
#  - bokeh
  - pip:
    - pgcontents
    - numpy
    - matplotlib
    - pandas
    - seaborn
    - bokeh
    - plotly
    - ggplot
    - git+git://github.com/ipython-contrib/jupyter_contrib_nbextensions.git
