   # bind ipython version (compatibility to pgcontents)
   - ipython = 5
   # get dependencies for pgcontents
   - certifi
   - click
   - cryptography 
   - mako
   - psycopg2
   - six
   - sqlalchemy
   - nose
 #  - numpy
 #  - matplotlib
 #  - pandas
 #  - seaborn
 #  - bokeh
   - conda:
     - pgcontents
     - numpy
     - matplotlib
     - pandas
     - seaborn
     - bokeh
     - git+git://github.com/ipython-contrib/jupyter_contrib_nbextensions.git
